head:
    prefix: certpublish

    label: I18N_OPENXPKI_WF_TYPE_CERTIFICATE_PUBLISHING

    description: I18N_OPENXPKI_WF_TYPE_CERTIFICATE_PUBLISHING_DESC


state:
    INITIAL: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_INITIAL_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_INITIAL_DESC
        action: 
          - initialize > WAITING_FOR_START

    PUBLISH: 
        autorun: 1
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_PUBLISH_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_PUBLISH_DESC
        action: 
          - publish > SUCCESS

    SUCCESS: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_SUCCESS_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_SUCCESS_DESC

    WAITING_FOR_START: 
        autorun: 1
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_WAITING_FOR_START_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_CERT_PUBLISH_WAITING_FOR_START_DESC
        action: 
          - global_disconnect > PUBLISH


action:
    initialize: 
        class: Workflow::Action::Null
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_I18N_OPENXPKI_WF_ACTION_CERTIFICATE_PUBLISHING_INITIALIZE_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_I18N_OPENXPKI_WF_ACTION_CERTIFICATE_PUBLISHING_INITIALIZE_DESC
        input: 
          - cert_identifier

    publish: 
        class: OpenXPKI::Server::Workflow::Activity::Tools::PublishCertificate
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_I18N_OPENXPKI_WF_ACTION_CERTIFICATE_PUBLISHING_PUBLISH_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_I18N_OPENXPKI_WF_ACTION_CERTIFICATE_PUBLISHING_PUBLISH_DESC
        input: 
          - cert_identifier
        param: 
            prefix: publishing.entity



acl:

    CA Operator: 
        creator: any

    RA Operator: 
        creator: any

    System: 
        creator: self

    User: 
        creator: self

