head:
    label: Change Certificate metadata
    description: Change the persisted metadata of certificates
    prefix: changemeta

state: 
    INITIAL:
        label: ''
        description: ''
        action: load_data > DATA_UPDATE
    
    DATA_UPDATE:
        action: update_context > CHOOSE_ACTION

    CHOOSE_ACTION:        
        action:
          - load_form > DATA_UPDATE
          - terminate > FAILURE
          - persist > SUCCESS

    FAILURE:
        label: Changes have been discarded

    SUCCESS:
        label: Changes have been persisted
        
action: 
    load_data:
        class: OpenXPKI::Server::Workflow::Activity::Tools::LoadCertificateMetadata
        label: Load existing data
        description: Please enter the certificate identifier or type your subject to find your certificate.
        input: cert_identifier
#        validator: global_cert_identifier

    load_form:
        label: Edit meta data
        class: OpenXPKI::Server::Workflow::Activity::Noop
    
    update_context:
        label: Update information
        description: Enter/update the given information and press the continue button if you are done. Fields marked with the blue plus sign can be added more than once.
        class: OpenXPKI::Server::Workflow::Activity::Noop
        input:
          - meta_email
          - meta_requestor
          - meta_system_id

        validator:
          - meta_email
#         - meta_system_id

    persist:
        label: Persist data
        class: OpenXPKI::Server::Workflow::Activity::Tools::UpdateCertificateMetadata

    terminate:
        label: Discard changes
        class: OpenXPKI::Server::Workflow::Activity::Noop

validator:
    meta_email:
        class: OpenXPKI::Server::Workflow::Validator::Regex
        param:
            regex: email
        arg:
          - $meta_email

field:
    meta_email:
        name: meta_email
        label: eMail Address
        placeholder: Enter eMail Address of the system owner
        tooltip: You can enter multiple address using the blue plus sign at the right
        type: email
        min: 1 
        max: 10

    meta_requestor:
        name: meta_requestor
        label: Requestor Name
        placeholder: The full name of the requestor, e.g. John Doe
        type: text 

    meta_system_id:
        name: meta_system_id        
        label: System Id
        required: 1
        placeholder: The systems infrastructure id or change number
        tooltip: If you do not know your systems id please ask the IT helpdesk.
        type: text 


