head:
    label: CRL Issue
    description: Create certificate revocation lists for all active tokens
    prefix: crl

state: 
    INITIAL:
        label: Create CRL
        description: CRLs are created when their age exceeds the configured update internval or when there are new revocations. You can check the "force issue" box to enforce issuance of CRLs.
        action: initialize > CREATE_QUEUE

    CREATE_QUEUE:
        autorun: 1
        action: create_queue > LOAD_NEXT_CA
        
    LOAD_NEXT_CA:
        autorun: 1
        action:
          - get_next_ca > ISSUE_CRL ? !ca_list_is_empty
          - global_noop > SUCCESS ? ca_list_is_empty

    ISSUE_CRL:
        autorun: 1
        action: nice_issue_crl > PUBLISH_CRL

    PUBLISH_CRL:
        autorun: 1
        action: publish_crl > LOAD_NEXT_CA

    SUCCESS:
        label: CRLs have been issued
        description: Navigate to the "Information" tab to get the issued CRLs.
        
        
action:
    initialize:
        label: The first Action
        description: I am first!
        class: OpenXPKI::Server::Workflow::Activity::Noop
        input: force_issue

    create_queue:
        class: OpenXPKI::Server::Workflow::Activity::CRLIssuance::CreateQueue

    get_next_ca:
        class: OpenXPKI::Server::Workflow::Activity::Tools::WFArray
        param:
            array_name: ca_alias_list
            context_key: ca_alias
            function: shift

    nice_issue_crl:
        class: OpenXPKI::Server::Workflow::Activity::NICE::IssueCRL
        param:
            retry_count: 10 
            retry_interval: +0000000030

    publish_crl:
        class: OpenXPKI::Server::Workflow::Activity::Tools::PublishCRL
        param:
            prefix: publishing.crl

condition:
    ca_list_is_empty:
        class: OpenXPKI::Server::Workflow::Condition::WFArray
        param:
            array_name: ca_alias_list
            condition: is_empty 

field:
    force_issue:
        name: force_issue
        type: bool
        label: Force Issue
        tooltip: Check this box to force issuance of CRLs

