head:
    label: I am a Test
    description: This is a Workflow for Testing
    prefix: test

state: 
    INITIAL:
        label: initial state
        description: This is where everything starts
        action: run_test1 > PENDING

    PENDING:
        label: pending state
        description: We hold here for a while
        action: global_run_test2 > SUCCESS
        
    SUCCESS:
        label: finals state
        description: It's done - really!
        
        
action:
    run_test1:
        label: The first Action
        description: I am first!
        class: Workflow::Action::Null  
        input: [ comment ]
        params:
            message: "Hi, I am a log message"


field:
    comment:
        label: Comment to Operator
        name: comment
        description: This it not used, yet
        placeholder: Please enter a comment here
        tooltip: Tell us what you think about it!
        type: textarea
        required: 1
