head:
    label: I am a Test
    description: This is a Workflow for Testing
    prefix: test

state: 
    INITIAL:
        label: initial state
        description: This is where everything starts
        action: run_test1 > PENDING

    PENDING:
        label: pending state
        description: We hold here for a while
        action: 
          - run_test2 > SUCCESS ? is_true
          - global_run_test2 > PENDING ? !is_true
        
    SUCCESS:
        label: finals state
        description: It's done - really!
        
        
action:
    run_test1:
        label: The first Action
        description: I am first!
        class: OpenXPKI::Server::Workflow::Activity::Noop
        param:
            message: "Hi, I am a log message"

    run_test2:
        label: The first alternative Action
        description: I am first!
        class: OpenXPKI::Server::Workflow::Activity::Noop
        input: comment
        validator: is_ascii
        param:
            message: "Hi, I am a log message"

condition:
    is_true:
        class: OpenXPKI::Server::Workflow::Condition::AlwaysTrue

# We combine argument and param in a single block
validator:
    is_ascii:
        class: OpenXPKI::Server::Workflow::Validator::Regex
        param:
            regex: \A (\w\s)+ \z
        args:
            - $comment

field:
    comment:
        label: Comment to Operator
        name: comment
        description: This it not used, yet
        placeholder: Please enter a comment here
        tooltip: Tell us what you think about it!
        type: textarea
        required: 1
