class: OpenXPKI::Server::Workflow::Activity::Tools::Disconnect
label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_I18N_OPENXPKI_WF_ACTION_TOOLS_DISCONNECT_LABEL
description: I18N_OPENXPKI_UI_WORKFLOW_ACTION_I18N_OPENXPKI_WF_ACTION_TOOLS_DISCONNECT_DESC
