Anonymous:
    create:
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_RENEWAL_REQUEST
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOCATION_REQUEST
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_SIGNING_REQUEST
    - I18N_OPENXPKI_WF_TYPE_ENROLLMENT

    access:            
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_RENEWAL_REQUEST:
            creator: self
        
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOCATION_REQUEST:
            creator: self
        
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_SIGNING_REQUEST:
            creator: self                
            
        I18N_OPENXPKI_WF_TYPE_ENROLLMENT:
            creator: self
            
System:
    create:
    - I18N_OPENXPKI_WF_TYPE_CRL_ISSUANCE
    - I18N_OPENXPKI_WF_TYPE_TESTING
    - I18N_OPENXPKI_WF_TYPE_CERT_EXPORT

    access:        
        I18N_OPENXPKI_WF_TYPE_CRL_ISSUANCE:
            creator: .*
        
        I18N_OPENXPKI_WF_TYPE_TESTING:
            creator: .*
            context:
                show: .*
                
        I18N_OPENXPKI_WF_TYPE_ENROLLMENT:                
            creator: .*        
      
        I18N_OPENXPKI_WF_TYPE_CERT_EXPORT:
            creator: .*
            
User:
    create:
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_RENEWAL_REQUEST
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOCATION_REQUEST
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_SIGNING_REQUEST
    - I18N_OPENXPKI_WF_TYPE_PASSWORD_SAFE
    - I18N_OPENXPKI_WF_TYPE_SMARTCARD_PERSONALIZATION_V4
    - I18N_OPENXPKI_WF_TYPE_SMARTCARD_PIN_UNBLOCK
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOKE

    access:            
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_RENEWAL_REQUEST:
            creator: self
            context:
                show: .*
                hide: approvals
        
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOCATION_REQUEST:
            creator: self
        
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_SIGNING_REQUEST:
            creator: self
            context:
                show: .*
                hide: approvals
         
        I18N_OPENXPKI_WF_TYPE_PASSWORD_SAFE:
            creator: self
            context:
                show: .*
                hide: encrypted_.*       

        I18N_OPENXPKI_WF_TYPE_SMARTCARD_PERSONALIZATION_V4:
            creator: .*
            context:
                show: .*
                hide: approvals
                
        I18N_OPENXPKI_WF_TYPE_SMARTCARD_PIN_UNBLOCK:
            creator: .*
                
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOKE:
            creator: .*

RA Operator:
    create:
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_PUBLISHING
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_RENEWAL_REQUEST
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOCATION_REQUEST
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_SIGNING_REQUEST
    - I18N_OPENXPKI_WF_TYPE_CRL_ISSUANCE
    - I18N_OPENXPKI_WF_TYPE_TESTING
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOKE
    - I18N_OPENXPKI_WF_TYPE_CHANGE_METADATA

    access:
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_PUBLISHING:
            creator: .*
            context:
                show: .*
            
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_RENEWAL_REQUEST:
            creator: .*
        
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOCATION_REQUEST:
            creator: .*
        
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_SIGNING_REQUEST:
            creator: .*
            context:
                show: .*
                # this is a policy decision, you may want to show the
                # reg officers who else has approved - or not, so as 
                # to not impair his or her judgement
                #hide: approvals
        
        I18N_OPENXPKI_WF_TYPE_CRL_ISSUANCE:
            creator: .*
        
        I18N_OPENXPKI_WF_TYPE_TESTING:
            creator: .*
            context:
                show: .*                 

        I18N_OPENXPKI_WF_TYPE_SMARTCARD_PERSONALIZATION_V4:
            creator: .*

        I18N_OPENXPKI_WF_TYPE_ENROLLMENT:
            creator: .*              
            
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOKE:
            creator: .*

        I18N_OPENXPKI_WF_TYPE_CHANGE_METADATA:
            creator: .*
        
CA Operator:
    create:
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_PUBLISHING
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_RENEWAL_REQUEST
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOCATION_REQUEST
    - I18N_OPENXPKI_WF_TYPE_CERTIFICATE_SIGNING_REQUEST
    - I18N_OPENXPKI_WF_TYPE_CRL_ISSUANCE
    - I18N_OPENXPKI_WF_TYPE_PASSWORD_SAFE
    - I18N_OPENXPKI_WF_TYPE_SCEP_REQUEST
    - I18N_OPENXPKI_WF_TYPE_TESTING

    access:
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_PUBLISHING:
            creator: .*
            
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_RENEWAL_REQUEST:
            creator: .*
        
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_REVOCATION_REQUEST:
            creator: .*
        
        I18N_OPENXPKI_WF_TYPE_CERTIFICATE_SIGNING_REQUEST:
            creator: .*
        
        I18N_OPENXPKI_WF_TYPE_CRL_ISSUANCE:
            creator: .*
        
        I18N_OPENXPKI_WF_TYPE_TESTING:
            creator: .*
        
        I18N_OPENXPKI_WF_TYPE_SMARTCARD_PERSONALIZATION_V4:
            creator: .*                       

