# The name of the file equals the name of the profile

validity:
    notafter: +0006

digest: sha1
increasing_serials: 1
randomized_serial_bytes: 8

style:
    00_user_basic_style:
        label: I18N_OPENXPKI_PROFILE_USER_BASIC_STYLE
        description: I18N_OPENXPKI_PROFILE_USER_BASIC_DESC

        subject:
            dn: cn=[% givenname %][% IF initials %] [% initials %][% END %] [% sn %],dc=My Company,dc=com
            san: 
               email: "[% mail %]"

        metadata:
            requestor: "[% givenname %] [% sn %]"
            email: "[% mail %]"

        
role:
- User

# Profile extensions - set 0/1 as needed
extensions:
    basic_constraints:
        critical: 1
        ca: 0

    key_usage:
        critical: 0
        digital_signature: 0
        non_repudiation:   0
        key_encipherment:  1
        data_encipherment: 1
        key_agreement:     0
        key_cert_sign:     0
        crl_sign:          0
        encipher_only:     0
        decipher_only:     0

    extended_key_usage:
        critical: 0
        client_auth:      0
        email_protection: 1
        oid: 1.3.6.1.4.1.311.20.2.2

    subject_key_identifier:
        critical: 0
        hash: 1

    authority_key_identifier:
        critical: 0
        keyid:  1
        issuer: 1

    issuer_alt_name:
        critical: 0
        # If the issuer has no subject alternative name, copying returns
        # an empty extension, which is problematic with both RSA SecurId
        # tokens and Cisco devices!
        copy: 1


    crl_distribution_points:
        critical: 0
        uri:
        - http://localhost/cacrl.crt
        - ldap://localhost/cn=My%20CA,dc=OpenXPKI,dc=org

    authority_info_access:
        critical: 0
        ca_issuers: http://localhost/cacert.crt
        ocsp: http://ocsp.openxpki.org/

    policy_identifier:
        critical: 0
        # WARNING: if use_loa is set to yes, the policy_identifier
        # will be extended by the values in the appropriate loa tag
        oid: 1.2.3.4

    cps:
        critical: 0
        # WARNING: if use_loa is set to yes, the cps will be
        # extended by the values in the appropriate loa tag
        uri: http://localhost/cps.html

    netscape:
        comment:
            critical: 0
            text: This is a generic certificate. Generated with OpenXPKI trustcenter software.
        certificate_type:
            critical: 0
            ssl_client:        1
            smime_client:      1
            object_signing:    0
            ssl_client_ca:     0
            smime_client_ca:   0
            object_signing_ca: 0

        cdp:
            critical: 0
            uri: http://localhost/cacrl.crt
            ca_uri: http://localhost/cacrl.crt

     # end of netscape section
# end of extensions

# Define the input fields you used below here
#template:


