label: I18N_OPENXPKI_UI_WORKFLOW_FIELD__PASSWORD_LABEL
name: _password
description: I18N_OPENXPKI_UI_WORKFLOW_FIELD__PASSWORD_DESC
placeholder: I18N_OPENXPKI_UI_WORKFLOW_FIELD__PASSWORD_PLACEHOLDER
tooltip: I18N_OPENXPKI_UI_WORKFLOW_FIELD__PASSWORD_TOOLTIP
required: 1
type: passwordverify
