label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_REASON_CODE_LABEL
name: reason_code
description: I18N_OPENXPKI_UI_WORKFLOW_FIELD_REASON_CODE_DESC
placeholder: I18N_OPENXPKI_UI_WORKFLOW_FIELD_REASON_CODE_PLACEHOLDER
tooltip: I18N_OPENXPKI_UI_WORKFLOW_FIELD_REASON_CODE_TOOLTIP
required: 1
type: select
option:
    item:
      - unspecified
      - keyCompromise
      - CACompromise
      - affiliationChanged
      - superseded
      - cessationOfOperation
    label: I18N_OPENXPKI_UI_WORKFLOW_FIELD_REASON_CODE_OPTION

